
spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    encoding: UTF-8
    mode: LEGACYHTML5
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filter: stat
      #mysql驱动
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://rm-bp19voh3j79q52965mo.mysql.rds.aliyuncs.com:3306/work?useSSL=true&autoReconnect=true
      username: jingjing
      password: Jj123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
#    driver-class-name: com.mysql.jdbc.Driver
#    username: jingjing
#    password: Jj123456
#    url: jdbc:mysql://rm-bp19voh3j79q52965mo.mysql.rds.aliyuncs.com:3306/work?useSSL=true&autoReconnect=true
  servlet:
    multipart:
      max-file-size: 10
      max-request-size: 100
  aop:
    auto: true
    proxy-target-class: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jingxiang.goods.entity
